"""document.py -- a lesson becomes a document.

Two things live here. The first is a small markdown-to-LaTeX converter, which
used to sit in `bin/board` and had to move the day the board itself needed it:
the export is a button on an iPad now, not only a command in a terminal, and the
server cannot import a script with no `.py` on the end of it.

The second is the thing that button does. `board export` used to write out the
tutor's cards and nothing else -- half a conversation, which is exactly what
`board archive` refuses to keep and for the same reason. What comes out now is
the whole sitting in reading order: the question, the working that was handed in
(every revision of it, as the picture that was actually sent), what the tutor
said about it, and the next attempt underneath. That is the artefact somebody
shows a professor, so it is a document rather than a screenshot, it is tracked in
git, and it is numbered rather than stamped with the time -- v1, v2, v3 of the
same lesson, because "which one is the latest" should not require reading a date.
"""

import json
import os
import re
import subprocess
import time

from .. import paths, reasoning, tex

# The tool's own directory, which is two levels up from here now. Derived in
# one place -- `paths.TOOL` -- rather than from this file's position, because a
# module that moves takes a hand-rolled `dirname(dirname(...))` with it and the
# only symptom is LaTeX not finding board-macros.tex.
TOOL = paths.TOOL


TEX_HEAD = r"""%% Generated by `board export` -- the transcript of a live lesson.
%% Both halves of it: the tutor's cards and the student's own working.
%%
%% The three packages this file needs beyond the course's own are loaded AFTER
%% coursemacros.sty and with no options, so that a course loading any of them
%% its own way wins and there is no option clash -- which is a fatal error, and
%% was one, the first time this was pointed at a real repository.
\PassOptionsToPackage{hidelinks}{hyperref}
\documentclass[11pt]{article}
%% A scalable font, before anything else: a course whose macros switch microtype
%% on gets font expansion, and font expansion against the default bitmap fonts is
%% a fatal error rather than a warning. The course's own font package, if it has
%% one, is loaded after this and wins.
\usepackage{lmodern}
\usepackage[T1]{fontenc}
\usepackage{amsmath,amssymb,amsthm,mathtools}
\usepackage[margin=1in]{geometry}
\usepackage{tikz}
%% Commutative diagrams, if this machine has them. A minimal TeX install ships
%% pgf but not tikz-cd, and requiring it unconditionally meant a missing package
%% used by one optional kind of fence took down EVERY export on that machine:
%% `! LaTeX Error: File 'tikz-cd.sty' not found`, on an evening's transcript that
%% contained no diagrams at all. A lesson that cannot be exported is a lesson
%% lost, so the whole document must not rest on a package it may not need.
\IfFileExists{tikz-cd.sty}{\usepackage{tikz-cd}}{}
\usetikzlibrary{arrows.meta,positioning,calc,fit,shapes.geometric}
%(macros)s\input{board-macros.tex}
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{hyperref}
\usepackage{needspace}
%% Who is speaking. A transcript in which the two voices look the same is a
%% transcript nobody can read: the tutor's cards are the prose, and the
%% student's own working is set off from it and labelled with whose it is.
\newenvironment{studentturn}[1]{%%
  \par\medskip\needspace{4\baselineskip}%%
  \noindent{\small\bfseries\sffamily #1}\par\nopagebreak\smallskip
  \begingroup\setlength{\leftskip}{1.2em}%%
}{\endgroup\par\medskip}
\title{%(title)s}
\author{%(author)s}
\date{%(date)s}
\begin{document}
\maketitle
"""

KIND_HEAD = {
    "question": "Your move",
    "correct": "Correct",
    "wrong": "Not quite",
    "review": "Review",
    "note": "Aside",
    "recap": "Recap",
}


def author_name(live):
    """Whose name goes on an exported lesson: state.json, then git, then nobody."""
    name = live.state().get("author")
    if name:
        return name
    try:
        p = subprocess.run(["git", "config", "user.name"], cwd=live.root,
                           stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, timeout=5)
        if p.returncode == 0:
            return p.stdout.decode("utf-8", "replace").strip()
    except (OSError, subprocess.TimeoutExpired):
        pass
    return ""


# ---------------------------------------------------------------------------
# Unicode, which pdflatex does not read
# ---------------------------------------------------------------------------
# A card is prose written by a model, on a board whose own buttons are labelled
# with arrows and check marks, in a subject whose prose is full of Greek. Every
# one of those characters is a FATAL error to pdflatex, not a warning -- an
# export that dies on a stray glyph is an export nobody can rely on, and the
# first real lesson this was pointed at died on the down-arrow in "save".
#
# So: the ones worth keeping are mapped to the command that draws them, in
# \ensuremath so they work in prose and inside math alike, and anything left
# over is dropped rather than allowed to stop the build. Latin-1 letters pass
# straight through; inputenc reads those.
UNICODE_TEX = {
    "\u2192": "\\rightarrow", "\u2190": "\\leftarrow", "\u2194": "\\leftrightarrow",
    "\u21d2": "\\Rightarrow", "\u21d0": "\\Leftarrow", "\u21d4": "\\Leftrightarrow",
    "\u2191": "\\uparrow", "\u2193": "\\downarrow", "\u21a6": "\\mapsto",
    "\u2913": "\\downarrow", "\u2912": "\\uparrow",
    "\u2264": "\\leq", "\u2265": "\\geq", "\u2260": "\\neq", "\u2248": "\\approx",
    "\u2261": "\\equiv", "\u221e": "\\infty", "\u00d7": "\\times", "\u00f7": "\\div",
    "\u00b1": "\\pm", "\u2213": "\\mp", "\u22c5": "\\cdot", "\u2218": "\\circ",
    "\u221a": "\\sqrt{}", "\u2211": "\\sum", "\u220f": "\\prod", "\u222b": "\\int",
    "\u2202": "\\partial", "\u2207": "\\nabla", "\u2205": "\\emptyset",
    "\u2208": "\\in", "\u2209": "\\notin", "\u2286": "\\subseteq", "\u2282": "\\subset",
    "\u2287": "\\supseteq", "\u2283": "\\supset", "\u222a": "\\cup", "\u2229": "\\cap",
    "\u2200": "\\forall", "\u2203": "\\exists", "\u00ac": "\\neg",
    "\u2227": "\\wedge", "\u2228": "\\vee", "\u2295": "\\oplus", "\u2297": "\\otimes",
    "\u2245": "\\cong", "\u223c": "\\sim", "\u2225": "\\parallel", "\u22a5": "\\perp",
    "\u2220": "\\angle", "\u00b0": "^\\circ", "\u2032": "'", "\u2033": "''",
    "\u211a": "\\mathbb{Q}", "\u211d": "\\mathbb{R}", "\u2124": "\\mathbb{Z}",
    "\u2115": "\\mathbb{N}", "\u2102": "\\mathbb{C}", "\u1d53d": "\\mathbb{F}",
    "\u03b1": "\\alpha", "\u03b2": "\\beta", "\u03b3": "\\gamma", "\u03b4": "\\delta",
    "\u03b5": "\\varepsilon", "\u03b6": "\\zeta", "\u03b7": "\\eta", "\u03b8": "\\theta",
    "\u03b9": "\\iota", "\u03ba": "\\kappa", "\u03bb": "\\lambda", "\u03bc": "\\mu",
    "\u03bd": "\\nu", "\u03be": "\\xi", "\u03c0": "\\pi", "\u03c1": "\\rho",
    "\u03c3": "\\sigma", "\u03c4": "\\tau", "\u03c5": "\\upsilon", "\u03c6": "\\varphi",
    "\u03c7": "\\chi", "\u03c8": "\\psi", "\u03c9": "\\omega",
    "\u0393": "\\Gamma", "\u0394": "\\Delta", "\u0398": "\\Theta", "\u039b": "\\Lambda",
    "\u039e": "\\Xi", "\u03a0": "\\Pi", "\u03a3": "\\Sigma", "\u03a6": "\\Phi",
    "\u03a8": "\\Psi", "\u03a9": "\\Omega",
}
UNICODE_TEXT = {
    "\u2014": "---", "\u2013": "--", "\u2026": "\\ldots{}", "\u00a0": "~",
    "\u2018": "`", "\u2019": "'", "\u201c": "``", "\u201d": "''",
    "\u2022": "\\textbullet{}", "\u00b7": "\\textperiodcentered{}",
    "\u2713": "[yes]", "\u2717": "[no]", "\u2717": "[no]", "\u2011": "-",
    "\u00ab": "\\guillemotleft{}", "\u00bb": "\\guillemotright{}",
}


def tex_unicode(s):
    """Make a string something pdflatex will actually read."""
    out = []
    for ch in s:
        if ord(ch) < 128 or 0xA0 < ord(ch) < 0x180:
            out.append(ch)
        elif ch in UNICODE_TEXT:
            out.append(UNICODE_TEXT[ch])
        elif ch in UNICODE_TEX:
            out.append("\\ensuremath{%s}" % UNICODE_TEX[ch])
        else:
            out.append("")            # better a missing glyph than no document
    return "".join(out)


def tex_escape(s):
    for a, b in (("\\", "\\textbackslash{}"), ("&", "\\&"), ("%", "\\%"),
                 ("#", "\\#"), ("_", "\\_"), ("{", "\\{"), ("}", "\\}")):
        s = s.replace(a, b)
    return s


def md_to_tex(body):
    """Enough markdown for a lesson transcript. Math and tikz pass through."""
    out = []
    lines = tex_unicode(body).replace("\r\n", "\n").split("\n")
    i = 0
    list_stack = []

    def close_lists(to=0):
        while len(list_stack) > to:
            out.append("\\end{%s}" % list_stack.pop())

    while i < len(lines):
        line = lines[i]

        m = re.match(r"^[ \t]*```[ \t]*(tikz|tikzcd|latex)[ \t]*$", line)
        if m:
            kind = m.group(1)
            i += 1
            buf = []
            while i < len(lines) and not re.match(r"^[ \t]*```", lines[i]):
                buf.append(lines[i])
                i += 1
            i += 1
            src = "\n".join(buf)
            if kind == "tikzcd" and "\\begin{tikzcd}" not in src:
                src = "\\begin{tikzcd}\n%s\n\\end{tikzcd}" % src
            elif kind == "tikz" and "\\begin{tikzpicture}" not in src and "\\begin{tikzcd}" not in src:
                src = "\\begin{tikzpicture}\n%s\n\\end{tikzpicture}" % src
            close_lists()
            out.append("\\begin{center}\n%s\n\\end{center}" % src)
            continue

        if not line.strip():
            close_lists()
            out.append("")
            i += 1
            continue

        h = re.match(r"^(#{1,6})\s+(.*)$", line)
        if h:
            close_lists()
            level = len(h[1])
            cmd = "subsection*" if level >= 2 else "section*"
            if level >= 3:
                cmd = "subsubsection*"
            out.append("\\%s{%s}" % (cmd, inline_tex(h[2])))
            i += 1
            continue

        if re.match(r"^\s*(-{3,}|\*{3,}|_{3,})\s*$", line):
            close_lists()
            out.append("\\medskip\\hrule\\medskip")
            i += 1
            continue

        # table
        if "|" in line and i + 1 < len(lines) and re.match(r"^\s*\|?[\s:|-]*-[\s:|-]*\|?\s*$", lines[i + 1]):
            close_lists()
            rows = []
            header = [c.strip() for c in line.strip().strip("|").split("|")]
            i += 2
            while i < len(lines) and "|" in lines[i] and lines[i].strip():
                rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
                i += 1
            spec = "l" * len(header)
            out.append("\\begin{center}\\begin{tabular}{%s}\\hline" % spec)
            out.append(" & ".join("\\textbf{%s}" % inline_tex(c) for c in header) + " \\\\ \\hline")
            for r in rows:
                out.append(" & ".join(inline_tex(c) for c in r) + " \\\\")
            out.append("\\hline\\end{tabular}\\end{center}")
            continue

        b = re.match(r"^(\s*)([-*+]|\d+[.)])\s+(.*)$", line)
        if b:
            depth = len(b[1]) // 2 + 1
            env = "enumerate" if re.match(r"\d", b[2]) else "itemize"
            while len(list_stack) > depth:
                out.append("\\end{%s}" % list_stack.pop())
            while len(list_stack) < depth:
                list_stack.append(env)
                out.append("\\begin{%s}" % env)
            out.append("  \\item " + inline_tex(b[3]))
            i += 1
            continue

        if line.lstrip().startswith(">"):
            close_lists()
            buf = []
            while i < len(lines) and lines[i].lstrip().startswith(">"):
                buf.append(re.sub(r"^\s*>\s?", "", lines[i]))
                i += 1
            out.append("\\begin{quote}\n%s\n\\end{quote}" % inline_tex(" ".join(buf)))
            continue

        close_lists()
        out.append(inline_tex(line))
        i += 1

    close_lists()
    return "\n".join(out)


def inline_tex(s):
    """Markdown emphasis and code to LaTeX, leaving math spans alone."""
    s = tex_unicode(s)
    parts = re.split(r"(\$\$.*?\$\$|\$[^$]*\$|\\\[.*?\\\]|\\\(.*?\\\))", s, flags=re.DOTALL)
    for n, part in enumerate(parts):
        if n % 2:
            continue
        part = re.sub(r"`([^`]+)`", lambda m: "\\texttt{%s}" % tex_escape(m.group(1)), part)
        part = re.sub(r"\*\*\*(.+?)\*\*\*", r"\\textbf{\\emph{\1}}", part)
        part = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", part)
        part = re.sub(r"(?<![\w*])\*([^*\n]+)\*(?![\w*])", r"\\emph{\1}", part)
        part = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", r"\\href{\2}{\1}", part)
        for a, b in (("&", "\\&"), ("%", "\\%"), ("#", "\\#")):
            part = part.replace(a, b)
        part = re.sub(r"(?<![\\{])_", r"\\_", part)
        parts[n] = part
    return "".join(parts)




# ---------------------------------------------------------------------------
# the conversation, both halves of it
# ---------------------------------------------------------------------------
CARD_RE = re.compile(r"^(\d{4})[-_.](.*)\.(md|markdown|tex)$")

SIGNAL_SAID = {
    "done": "ready to check",
    "help": "asked for help",
    "confused": "said they were lost",
    "begin": "asked the tutor to begin",
    "skip": "skipped this one",
}


def front_matter(raw):
    """The `---` block at the top of a card, and the body under it."""
    meta = {}
    text = raw
    if raw.startswith("---"):
        end = raw.find("\n---", 3)
        if end != -1:
            for line in raw[3:end].splitlines():
                if ":" in line:
                    k, v = line.split(":", 1)
                    meta[k.strip().lower()] = v.strip()
            text = raw[end + 4:].lstrip("\n")
    return meta, text


def read_cards(folder):
    """Every card in one lesson folder, in the order they were written."""
    out = []
    try:
        names = sorted(n for n in os.listdir(folder) if CARD_RE.match(n))
    except OSError:
        return out
    for n in names:
        try:
            with open(os.path.join(folder, n), "r", encoding="utf-8") as fh:
                raw = fh.read()
            st = os.stat(os.path.join(folder, n))
        except OSError:
            continue
        meta, text = front_matter(raw)
        # The same gate the board reads through: a document is not the place to
        # preserve a model's private working either.
        text = reasoning.card_body(text)
        out.append({"id": CARD_RE.match(n).group(1),
                    "kind": (meta.get("kind") or "lesson").lower(),
                    "title": meta.get("title", ""),
                    "body": text,
                    "mtime": st.st_mtime})
    return out


def read_turns(path):
    """EVERY revision of every turn, oldest first.

    The board collapses a turn to its newest revision, because three sends of one
    proof are one attempt and showing three is a lie about how many times the
    student answered. A document read by somebody who was not there is the
    opposite case: the point of it is the work, and the work is the sequence --
    what was handed in, what came back, what changed. So nothing is collapsed
    here, and each revision says which attempt it is.
    """
    out = []
    try:
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except ValueError:
                    continue
                if rec.get("id"):
                    out.append(rec)
    except OSError:
        return []
    out.sort(key=lambda r: (r.get("t") or 0, r.get("rev") or 0))
    return out


def reading_order(cards, turns):
    """Cards and turns interleaved the way the board reads them on screen.

    A turn belongs under the question it answers, whatever time it arrived --
    which is the rule the board itself uses, and it matters here because a
    student who goes back to an earlier exercise must not have that answer filed
    at the end of the document, half an hour of somebody else's questions away
    from the thing it is answering.
    """
    at = {}
    for n, c in enumerate(cards):
        at[c["id"]] = n
    items = []
    for n, c in enumerate(cards):
        items.append((n, 0, c.get("mtime") or 0, "card", c))
    for t in turns:
        when = t.get("t") or 0
        if t.get("answers") in at:
            pos = at[t["answers"]]
        else:
            pos = -1
            for n, c in enumerate(cards):
                if (c.get("mtime") or 0) <= when:
                    pos = n
        items.append((pos, 1, when, "turn", t))
    items.sort(key=lambda it: (it[0], it[1], it[2]))
    return [(kind, obj) for _, _, _, kind, obj in items]


def _attempt_numbers(turns):
    """Which attempt each revision is, per question, in time order."""
    seen = {}
    out = {}
    for t in turns:
        if t.get("kind") not in ("ink", "text"):
            continue
        q = t.get("answers") or ""
        seen[q] = seen.get(q, 0) + 1
        out[id(t)] = seen[q]
    return out


def _picture(answers_dir, url):
    """One handed-in page, as the picture that was actually sent.

    Relative to the repository root, never absolute: the `.tex` is committed
    beside the PNGs it names, so it has to still build on somebody else's
    machine. `build` runs LaTeX from the root for exactly this reason.
    """
    if not url:
        return None
    name = url.split("/answers/", 1)[-1]
    path = os.path.join(answers_dir, name)
    if not os.path.exists(path):
        return None
    return path


def render_lesson(cards_dir, turns_path, answers_dir, root, heading=None):
    """One sitting as LaTeX: the questions, the working, and the replies."""
    cards = read_cards(cards_dir)
    turns = read_turns(turns_path)
    if not cards and not turns:
        return []
    attempt = _attempt_numbers(turns)
    of = {}
    for t in turns:
        if id(t) in attempt:
            q = t.get("answers") or ""
            of[q] = max(of.get(q, 0), attempt[id(t)])

    body = []
    if heading:
        body.append("\\section{%s}" % inline_tex(heading))
    for kind, obj in reading_order(cards, turns):
        if kind == "card":
            head = KIND_HEAD.get(obj["kind"])
            label = " -- ".join(x for x in (head, obj["title"]) if x)
            if label:
                body.append("\\needspace{3\\baselineskip}\\subsection*{%s}"
                            % inline_tex(label))
            body.append(md_to_tex(obj["body"]))
            body.append("")
            continue

        t = obj
        who = "You" if (t.get("from") or "student") == "student" else "The tutor"
        n, total = attempt.get(id(t)), of.get(t.get("answers") or "", 0)
        when = t.get("iso") or ""
        if t.get("kind") == "ink":
            say = "%s wrote" % who
            if total > 1 and n:
                say += " -- attempt %d of %d" % (n, total)
            if when:
                say += ", %s" % when
            path = _picture(answers_dir, t.get("png"))
            body.append("\\begin{studentturn}{%s}" % inline_tex(say))
            if path:
                body.append("\\begin{center}\\includegraphics"
                            "[width=0.95\\linewidth,height=0.78\\textheight,"
                            "keepaspectratio]{%s}\\end{center}"
                            % os.path.relpath(path, root).replace("\\", "/"))
            else:
                body.append("\\emph{(the page this answer was written on is not "
                            "in this repository)}")
            body.append("\\end{studentturn}")
            body.append("")
        elif t.get("kind") == "text":
            said = SIGNAL_SAID.get(t.get("signal") or "")
            say = "%s said" % who
            if total > 1 and n:
                say += " -- attempt %d of %d" % (n, total)
            if when:
                say += ", %s" % when
            body.append("\\begin{studentturn}{%s}" % inline_tex(say))
            if said and not (t.get("text") or "").strip():
                body.append("\\emph{%s}" % inline_tex(said))
            else:
                if said:
                    body.append("\\emph{%s}\\par\\smallskip" % inline_tex(said))
                body.append(md_to_tex(t.get("text") or ""))
            body.append("\\end{studentturn}")
            body.append("")
        elif t.get("kind") == "annotation":
            say = "%s marked up the card" % who
            if when:
                say += ", %s" % when
            path = _picture(answers_dir, t.get("png"))
            body.append("\\begin{studentturn}{%s}" % inline_tex(say))
            if path:
                body.append("\\begin{center}\\includegraphics"
                            "[width=0.95\\linewidth,height=0.5\\textheight,"
                            "keepaspectratio]{%s}\\end{center}"
                            % os.path.relpath(path, root).replace("\\", "/"))
            body.append("\\end{studentturn}")
            body.append("")
    return body


# ---------------------------------------------------------------------------
# where it goes, and what it is called
# ---------------------------------------------------------------------------
OUT_DIR = "transcripts"


def slugify(s):
    s = re.sub(r"[^A-Za-z0-9]+", "-", (s or "").strip().lower()).strip("-")
    return (s or "lesson")[:48]


def next_version(out_dir, stem):
    """v1, v2, v3 -- and never a timestamp.

    Asked for in those words: a name stamped with the time is an eyesore and it
    does not answer the only question anybody asks of a folder of exports, which
    is which one is the latest. The number is one more than the highest already
    there, counting both halves of a pair, so a `.tex` written by a build whose
    LaTeX then failed still consumes its number rather than being quietly
    overwritten by the next attempt.
    """
    high = 0
    try:
        names = os.listdir(out_dir)
    except OSError:
        return 1
    pat = re.compile(re.escape(stem) + r"-v(\d+)\.(pdf|tex)$")
    for n in names:
        m = pat.match(n)
        if m:
            high = max(high, int(m.group(1)))
    return high + 1


def read_state(path):
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh) or {}
    except (OSError, ValueError):
        return {}


def lessons(root, scope="lesson"):
    """The sittings to put in the document, oldest first.

    A lesson is the unit -- one sitting, one document, numbered v1, v2, v3 as it
    is exported again. `scope="all"` is the other thing somebody shows a
    professor: every filed lesson in the course, then the one still open, as a
    single master document.
    """
    live = os.path.join(root, "live")
    here = {"cards": os.path.join(live, "cards"),
            "turns": os.path.join(live, "turns.jsonl"),
            "answers": os.path.join(live, "answers"),
            "state": read_state(os.path.join(live, "state.json"))}
    if scope != "all":
        return [here]
    out = []
    archive = os.path.join(live, "archive")
    try:
        names = sorted(os.listdir(archive))
    except OSError:
        names = []
    for name in names:
        folder = os.path.join(archive, name)
        if not os.path.isdir(folder):
            continue
        out.append({"cards": folder,
                    "turns": os.path.join(folder, "turns.jsonl"),
                    "answers": os.path.join(folder, "answers"),
                    "state": read_state(os.path.join(folder, "state.json")),
                    "filed": name})
    if read_cards(here["cards"]) or read_turns(here["turns"]):
        out.append(here)
    return out


def author_name(root, state):
    """Whose name goes on it: state.json, then git, then nobody."""
    if state.get("author"):
        return state["author"]
    try:
        p = subprocess.run(["git", "config", "user.name"], cwd=root,
                           stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, timeout=5)
        if p.returncode == 0:
            return p.stdout.decode("utf-8", "replace").strip()
    except (OSError, subprocess.TimeoutExpired):
        pass
    return ""


def heading_for(sitting):
    """A lesson's name in the master document.

    Two sittings on the same chapter are the ordinary case -- an exercise runs
    over two evenings -- so the heading has to separate them, and `state.json`
    cannot: the live one carries whatever `opened` said when the chapter was
    opened, which is the same string. The archive folder is stamped with the
    moment the lesson was FILED, which is the one thing that differs, and the
    lesson still open says so in words rather than borrowing a date.
    """
    st = sitting.get("state") or {}
    bits = [st.get("chapter") or st.get("course") or "Lesson"]
    kind = st.get("session") or ""
    if kind and kind != "lecture":
        bits.append(kind.replace("_", " "))
    label = " -- ".join(bits)
    filed = sitting.get("filed") or ""
    m = re.match(r"^(\d{4})(\d{2})(\d{2})-(\d{2})(\d{2})", filed)
    if m:
        return "%s (%s-%s-%s %s:%s)" % (label, m.group(1), m.group(2), m.group(3),
                                        m.group(4), m.group(5))
    when = st.get("opened") or ""
    return label + (" (in progress)" if not filed else (" (%s)" % when if when else ""))


def compile_pdf(root, tex_path):
    """Twice, from the repository root, so relative image paths resolve."""
    env = tex.tex_env([os.path.join(root, "latex"), os.path.join(TOOL, "tex")])
    outdir = os.path.dirname(tex_path)
    pdf = os.path.splitext(tex_path)[0] + ".pdf"
    rel = os.path.relpath(tex_path, root)
    out = ""
    for _ in range(2):
        try:
            p = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", "-halt-on-error",
                 "-output-directory=" + os.path.relpath(outdir, root), rel],
                cwd=root, env=env, stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT, timeout=300)
            out = p.stdout.decode("utf-8", "replace")
        except (OSError, subprocess.TimeoutExpired) as e:
            return False, "could not run pdflatex: %s" % e
    if not os.path.exists(pdf):
        log = os.path.splitext(tex_path)[0] + ".log"
        detail = ""
        if os.path.exists(log):
            with open(log, "r", encoding="utf-8", errors="replace") as fh:
                detail = "".join(ln for ln in fh if ln.startswith("!"))[:500]
        # The log stays -- it is the only account of what went wrong -- but the
        # rest of the scratch does not.
        for ext in (".aux", ".out", ".toc"):
            try:
                os.remove(os.path.splitext(tex_path)[0] + ext)
            except OSError:
                pass
        return False, (detail or out[-500:] or "LaTeX produced no PDF")
    # The aux files are not the document and have no business in the history.
    for ext in (".aux", ".out", ".toc", ".log"):
        try:
            os.remove(os.path.splitext(tex_path)[0] + ext)
        except OSError:
            pass
    return True, pdf


def track(root, paths):
    """Stage the export, so the next push carries it.

    Staged rather than committed: an export happens in the middle of a lesson and
    a commit in the middle of a lesson is a decision the person makes, not one a
    button makes for them. `board push` -- and the board's own save -- commit
    everything staged, so this goes with the next one either way.
    """
    rel = [os.path.relpath(p, root) for p in paths if os.path.exists(p)]
    if not rel:
        return False
    try:
        p = subprocess.run(["git", "add", "--"] + rel, cwd=root,
                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=30)
        return p.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def build(root, scope="lesson", make_pdf=True):
    """The whole conversation as one document, numbered and tracked.

    Returns a record the board can paint: what it is called, whether LaTeX
    agreed, and where it went.
    """
    sittings = lessons(root, scope)
    sittings = [s for s in sittings
                if read_cards(s["cards"]) or read_turns(s["turns"])]
    if not sittings:
        return {"ok": False, "detail": "there is no lesson here to export yet"}

    last = sittings[-1]["state"] or {}
    course = last.get("course") or os.path.basename(root)
    if scope == "all":
        title = course
        stem = slugify(course) + "-complete"
    else:
        title = last.get("chapter") or course or "Lesson"
        stem = slugify(title)

    body = []
    for s in sittings:
        body.extend(render_lesson(s["cards"], s["turns"], s["answers"], root,
                                  heading_for(s) if scope == "all" else None))

    out_dir = os.path.join(root, OUT_DIR)
    os.makedirs(out_dir, exist_ok=True)
    version = next_version(out_dir, stem)
    name = "%s-v%d" % (stem, version)
    tex_path = os.path.join(out_dir, name + ".tex")

    sty = os.path.join(root, "latex", "coursemacros.sty")
    with open(tex_path, "w", encoding="utf-8") as fh:
        fh.write(TEX_HEAD % {
            "title": inline_tex(title),
            "author": inline_tex(author_name(root, last)),
            "date": time.strftime("%B %d, %Y"),
            "macros": "\\usepackage{coursemacros}\n" if os.path.exists(sty) else "",
        })
        if scope == "all":
            fh.write("\\tableofcontents\n\\clearpage\n")
        fh.write("\n".join(body))
        fh.write("\n\\end{document}\n")

    rec = {"ok": True, "name": name, "version": version, "scope": scope,
           "tex": os.path.relpath(tex_path, root), "pdf": None, "detail": ""}
    if make_pdf:
        ok, res = compile_pdf(root, tex_path)
        if ok:
            rec["pdf"] = os.path.relpath(res, root)
        else:
            rec["ok"] = False
            rec["detail"] = res
    rec["tracked"] = track(root, [tex_path,
                                  os.path.join(out_dir, name + ".pdf")])
    return rec
