#!/usr/bin/env python3
"""
sync-macros.py -- generate tex/board-macros.tex from web/macros.js.

The board renders mathematics twice: KaTeX in the browser for everything inline,
and real LaTeX for anything inside a tikz fence. Those are different engines, and
a command that works in one and not the other is the most annoying possible bug:
the prose renders, the diagram silently fails.

So the TeX side is generated from the KaTeX side rather than maintained beside
it. Every macro comes out as \\providecommand, which means a course repository's
own coursemacros.sty still wins -- this only fills the gaps.

    python3 tools/sync-macros.py          write the file
    python3 tools/sync-macros.py --check  exit 1 if it is out of date
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "web", "macros.js")
OUT = os.path.join(HERE, "tex", "board-macros.tex")

# KaTeX understands these; plain LaTeX needs them spelled differently or not at
# all. Anything mapped to None is skipped.
OVERRIDE = {
    "\\hl": None,        # \colorbox around displaystyle: KaTeX-only convenience
    "\\given": None,     # only legal inside \left ... \right
}

HEADER = r"""%% ==========================================================================
%%  board-macros.tex -- GENERATED by tools/sync-macros.py. Do not edit.
%%
%%  The macro vocabulary the board renders with, in a form real LaTeX can use,
%%  so a command that works in the prose also works inside a tikz fence.
%%
%%  Every definition is \providecommand: a course repository's own
%%  coursemacros.sty is loaded first and always wins. This only fills gaps.
%% ==========================================================================
\ProvidesFile{board-macros.tex}[Tutor-Board macro vocabulary]
"""


def parse_macros(text):
    """The macro table is a plain object literal; read it without executing JS."""
    m = re.search(r"window\.BOARD_MACROS\s*=\s*\{(.*?)\n\};", text, re.DOTALL)
    if not m:
        raise SystemExit("could not find window.BOARD_MACROS in " + SRC)
    body = m.group(1)
    out = []
    for line in body.split("\n"):
        line = line.strip()
        if not line or line.startswith("/*") or line.startswith("*") or line.startswith("//"):
            continue
        entry = re.match(r'^"((?:[^"\\]|\\.)*)"\s*:\s*"((?:[^"\\]|\\.)*)"\s*,?\s*$', line)
        if not entry:
            continue
        name = json.loads('"%s"' % entry.group(1))
        defn = json.loads('"%s"' % entry.group(2))
        out.append((name, defn))
    return out


def arity(defn):
    n = 0
    for i in range(1, 10):
        if "#%d" % i in defn:
            n = i
    return n


def render(macros):
    lines = [HEADER]
    for name, defn in macros:
        if name in OVERRIDE:
            if OVERRIDE[name] is None:
                continue
            defn = OVERRIDE[name]
        n = arity(defn)
        args = "[%d]" % n if n else ""
        lines.append("\\providecommand{%s}%s{%s}" % (name, args, defn))
    lines.append("")
    lines.append("\\endinput")
    lines.append("")
    return "\n".join(lines)


def main(argv):
    macros = parse_macros(open(SRC, encoding="utf-8").read())
    text = render(macros)
    if "--check" in argv:
        try:
            current = open(OUT, encoding="utf-8").read()
        except OSError:
            current = ""
        if current != text:
            print("tex/board-macros.tex is out of date; run tools/sync-macros.py",
                  file=sys.stderr)
            return 1
        print("%d macros, tex/board-macros.tex is current" % len(macros))
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s (%d macros)" % (os.path.relpath(OUT, HERE), len(macros)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
